apiVersion: v1
kind: Service
metadata:
  name: storeapi
  namespace: storeapi-qa
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: storeapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeapi
  namespace: storeapi-qa
spec:
  selector:
    matchLabels:
      app: storeapi
  template:
    metadata:
      labels:
        app: storeapi
    spec:
      containers:
        - name: storeapi
          image: ghcr.io/betuelsa/avature-storeapi:qa-19-d33f9e0-1725299892 # {"$imagepolicy": "flux-system:storeapi-qa"}
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
            - name: MONGO_DB
              value: "restdb"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: ghcr
